### ISSUE TITLE
Groovy script at end of doc job failed due to UnapprovedUsageException

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#166]
Groovy script at end of doc job failed

http://build.ros.org/job/Idoc__ueye__ubuntu_trusty_amd64/configure

```
[ssh-agent] Stopped.
ERROR: Failed to evaluate groovy script.
org.jenkinsci.plugins.scriptsecurity.scripts.UnapprovedUsageException: script not yet approved for use
        at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval.using(ScriptApproval.java:428)
        at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:166)
        at org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder.perform(GroovyPostbuildRecorder.java:362)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
        at hudson.model.Build$BuildExecution.post2(Build.java:185)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
        at hudson.model.Run.execute(Run.java:1766)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:98)
        at hudson.model.Executor.run(Executor.java:408)
Build step 'Groovy Postbuild' changed build result to FAILURE
Build step 'Groovy Postbuild' marked build as failure
```

There are many other instances: 
http://build.ros.org/job/Idoc__catkin__ubuntu_trusty_amd64/10/
http://build.ros.org/job/Idoc__ueye__ubuntu_trusty_amd64/6/
http://build.ros.org/job/Idoc__nao_robot__ubuntu_trusty_amd64/7/
http://build.ros.org/job/Idev__rtmros_hironx__ubuntu_trusty_amd64/4/
http://build.ros.org/job/Idoc__barrett_hand__ubuntu_trusty_amd64/6/
http://build.ros.org/job/Idoc__nao_moveit_config__ubuntu_trusty_amd64/7/
http://build.ros.org/job/Jdoc__patrolling_sim__ubuntu_trusty_amd64/7/
http://build.ros.org/job/Jdoc__navigation_2d__ubuntu_trusty_amd64/1/

**Comment by tfoote** [comment]
References: 
https://wiki.jenkins-ci.org/display/JENKINS/Script+Security+Plugin
and 
https://wiki.jenkins-ci.org/display/JENKINS/Groovy+Postbuild+Plugin

The groovy script required clicking approve here: http://build.ros.org/scriptApproval/

I don't know why this changed and needed approval: 

![script approval](https://cloud.githubusercontent.com/assets/447804/12593333/685c8044-c425-11e5-9674-636c9c56708b.png)

**Comment by tfoote** [comment]
I think we need to whitelist the methods we plan to use and then run the scripts in the sandbox.

**Comment by tfoote** [comment]
I think we need to add the methods here: /var/lib/jenkins/secrets/whitelisted-callables.d

**Comment by mikaelarguedas** [comment]
Can this be closed ? I think that when we upgraded to groovy2 we had to approve every single method.
The deployment configuration changed related to these approval is already ticketed [here](https://github.com/ros-infrastructure/buildfarm_deployment/issues/147)

**Comment by tfoote** [comment]
We should keep this open so we make sure to get an automated solution for deployment not just having fixed it manually for our current instance.

**Comment by dirk-thomas** [comment]
> We should keep this open so we make sure to get an automated solution for deployment not just having fixed it manually for our current instance.

Isn't that exactly what the ticket @mikaelarguedas created [here](https://github.com/ros-infrastructure/buildfarm_deployment/issues/147) is all about? We could keep this ticket for visibility but it is clearly a duplicate.

**Comment by tfoote** [comment]
Sorry yes that fully covers this.
