### ISSUE TITLE
needs to be released

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/ros_buildfarm#266]
The current released version is `1.0.0-1` in packages.ros.org. That fails when doing a prerelease for Kinetic with this:

```
% generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml \
  kinetic default ubuntu xenial amd64 \
  ros_tutorials \
  --level 2 \
  --output-dir ./
Fetching buildfarm configuration...
Fetching rosdistro cache...
Traceback (most recent call last):
  File "/usr/bin/generate_prerelease_script.py", line 286, in <module>
    sys.exit(main())
  File "/usr/bin/generate_prerelease_script.py", line 84, in main
    release_build_files = get_release_build_files(config, args.rosdistro_name)
  File "/usr/lib/python2.7/dist-packages/ros_buildfarm/config/__init__.py", line 71, in get_release_build_files
    build_files[k] = ReleaseBuildFile(k, v)
  File "/usr/lib/python2.7/dist-packages/ros_buildfarm/config/release_build_file.py", line 96, in __init__
    assert isinstance(self.package_blacklist, list)
AssertionError
```

**Comment by dirk-thomas** [comment]
Released 1.1.0.
