### ISSUE TITLE
rosdistro cache upload is not atomic

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/ros_buildfarm#270]
While one job tried to download the cache (http://build.ros.org/job/Jbin_uV64__roscpp__ubuntu_vivid_amd64__binary/4/console#console-section-11) a new cache was uploaded (http://build.ros.org/job/jade_rosdistro-cache/20099/console). My assumption is that the download failed since the uploade / replacement is not happening atomically.

For the record the exact error message:

```
# BEGIN SUBSECTION: get sourcedeb
# END SUBSECTION
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/release/get_sourcedeb.py", line 32, in <module>
    sys.exit(main())
  File "/tmp/ros_buildfarm/scripts/release/get_sourcedeb.py", line 28, in main
    args.sourcedeb_dir, args.skip_download_sourcedeb)
  File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 27, in get_sourcedeb
    dist_cache = get_distribution_cache(index, rosdistro_name)
  File "/usr/lib/python3/dist-packages/rosdistro/__init__.py", line 180, in get_distribution_cache
    yaml_str = f.read()
  File "/usr/lib/python3.4/gzip.py", line 360, in read
    while self._read(readsize):
  File "/usr/lib/python3.4/gzip.py", line 449, in _read
    self._read_eof()
  File "/usr/lib/python3.4/gzip.py", line 482, in _read_eof
    crc32, isize = struct.unpack("<II", self._read_exact(8))
  File "/usr/lib/python3.4/gzip.py", line 286, in _read_exact
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by dirk-thomas** [comment]
All the failed jobs fall into a five minute window. So it looks like that one uploaded cache was inconsistent and the next uploaded fixed the problem.

**Comment by dirk-thomas** [comment]
Since we haven't seen this again I will close this ticket for now. Please feel free to comment here if you see this again.
