### ISSUE TITLE
[version 1.2.0-1] IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/dist-packages/ros_buildfarm/wrapper/apt.py'

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/ros_buildfarm#347]
I got this error. Hope I'm just doing something wrong but can't think of it. Any idea to fix this is appreciated.
```
$ dpkg -p python-ros-buildfarm
Package: python-ros-buildfarm
Priority: optional
Section: python
Installed-Size: 865
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Architecture: all
Version: 1.2.0-1
Depends: python (>= 2.7), python (<< 2.8), python-catkin-pkg (>= 0.2.6), python-empy, python-yaml, python-rosdistro (>= 0.4.0), python-argparse
Conflicts: python3-ros-buildfarm
Size: 117782
:
rosnoodle@buillon:/tmp/prerelease1$ sudo apt-get install --reinstall python-ros-buildfarm
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/118 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 502539 files and directories currently installed.)
Preparing to unpack .../python-ros-buildfarm_1.2.0-1_all.deb ...
Unpacking python-ros-buildfarm (1.2.0-1) over (1.2.0-1) ...
Setting up python-ros-buildfarm (1.2.0-1) ...
rosnoodle@buillon:/tmp/prerelease1$ generate_prerelease_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml kinetic default ubuntu xenial amd64 geometric_shapes  --level 0   --output-dir ./ 
Fetching buildfarm configuration...
Fetching rosdistro cache...
Evaluating job templates...
IOError processing template 'devel/devel_job.xml.em'
Traceback (most recent call last):
  File "/usr/bin/generate_prerelease_script.py", line 299, in <module>
    sys.exit(main())
  File "/usr/bin/generate_prerelease_script.py", line 193, in main
    build_targets=release_targets_combined)
  File "/usr/lib/python2.7/dist-packages/ros_buildfarm/devel_job.py", line 305, in configure_devel_job
    is_disabled=is_disabled)
  File "/usr/lib/python2.7/dist-packages/ros_buildfarm/devel_job.py", line 392, in _get_devel_job_config
    job_config = expand_template(template_name, job_data)
  File "/usr/lib/python2.7/dist-packages/ros_buildfarm/templates/__init__.py", line 92, in expand_template
    data['wrapper_scripts'] = get_wrapper_scripts()
  File "/usr/lib/python2.7/dist-packages/ros_buildfarm/templates/__init__.py", line 168, in get_wrapper_scripts
    with open(abs_file_path, 'r') as h:
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/dist-packages/ros_buildfarm/wrapper/apt.py'
rosnoodle@buillon:/tmp/prerelease1$ ll /usr/lib/python2.7/dist-packages/ros_buildfarm/
total 428K
drwxr-xr-x   4 root root 4.0K Oct 20 11:13 ./
-rw-r--r--   1 root root  11K Oct 20 11:13 doc_job.pyc
-rw-r--r--   1 root root 3.3K Oct 20 11:13 debian_repo.pyc
-rw-r--r--   1 root root 8.1K Oct 20 11:13 jenkins.pyc
-rw-r--r--   1 root root 3.7K Oct 20 11:13 prerelease.pyc
-rw-r--r--   1 root root  788 Oct 20 11:13 release_common.pyc
-rw-r--r--   1 root root 2.5K Oct 20 11:13 status_page_input.pyc
-rw-r--r--   1 root root  21K Oct 20 11:13 status_page.pyc
drwxr-xr-x   2 root root 4.0K Oct 20 11:13 config/
-rw-r--r--   1 root root 2.3K Oct 20 11:13 crumb_requester.pyc
drwxr-xr-x   9 root root 4.0K Oct 20 11:13 templates/
-rw-r--r--   1 root root  11K Oct 20 11:13 argument.pyc
-rw-r--r--   1 root root  20K Oct 20 11:13 release_job.pyc
-rw-r--r--   1 root root 9.7K Oct 20 11:13 devel_job.pyc
-rw-r--r--   1 root root 1.6K Oct 20 11:13 jenkins_credentials.pyc
-rw-r--r--   1 root root  177 Oct 20 11:13 _version.pyc
-rw-r--r--   1 root root 2.2K Oct 20 11:13 catkin_workspace.pyc
-rw-r--r--   1 root root  17K Oct 20 11:13 common.pyc
-rw-r--r--   1 root root 4.7K Oct 20 11:13 git.pyc
-rw-r--r--   1 root root  211 Oct 20 11:13 __init__.pyc
-rw-r--r--   1 root root 3.3K Oct 20 11:13 sourcedeb_job.pyc
-rw-r--r--   1 root root 3.5K Oct 20 11:13 trigger_job.pyc
-rw-r--r--   1 root root 5.4K Oct 20 11:13 binarydeb_job.pyc
-rw-r--r--   1 root root 4.1K Oct 20 11:13 rosdoc_index.pyc
drwxr-xr-x 163 root root  16K Oct 20 11:11 ../
-rw-r--r--   1 root root  787 Oct  5 04:55 _version.py
-rw-r--r--   1 root root  18K Oct  1 08:52 common.py
-rw-r--r--   1 root root 7.3K Oct  1 08:42 argument.py
-rw-r--r--   1 root root  16K Oct  1 08:42 devel_job.py
-rw-r--r--   1 root root  17K Oct  1 08:42 doc_job.py
-rw-r--r--   1 root root  35K Sep 30 02:58 release_job.py
-rw-r--r--   1 root root 6.7K Sep 27 01:49 binarydeb_job.py
-rw-r--r--   1 root root 2.7K Sep 27 01:49 catkin_workspace.py
-rw-r--r--   1 root root 2.0K Sep 27 01:49 crumb_requester.py
-rw-r--r--   1 root root 3.4K Sep 27 01:49 debian_repo.py
-rw-r--r--   1 root root 5.7K Sep 27 01:49 git.py
-rw-r--r--   1 root root  653 Sep 27 01:49 __init__.py
-rw-r--r--   1 root root 1.8K Sep 27 01:49 jenkins_credentials.py
-rw-r--r--   1 root root 9.3K Sep 27 01:49 jenkins.py
-rw-r--r--   1 root root 5.6K Sep 27 01:49 prerelease.py
-rw-r--r--   1 root root 1.1K Sep 27 01:49 release_common.py
-rw-r--r--   1 root root 4.7K Sep 27 01:49 rosdoc_index.py
-rw-r--r--   1 root root 4.2K Sep 27 01:49 sourcedeb_job.py
-rw-r--r--   1 root root 3.6K Sep 27 01:49 status_page_input.py
-rw-r--r--   1 root root  26K Sep 27 01:49 status_page.py
-rw-r--r--   1 root root 5.3K Sep 27 01:49 trigger_job.py
```

**Comment by 130s** [comment]
Another person seems to have got the same error https://github.com/ros-planning/geometric_shapes/issues/61#issuecomment-254997733

**Comment by rhaschke** [comment]
@130s Looks like the `wrapper` folder is not correctly deployed. Manually copying the files from https://github.com/ros-infrastructure/ros_buildfarm/tree/master/ros_buildfarm/wrapper, solved the issue for me.

**Comment by rhaschke** [comment]
dependency package `em` is also not installed.

**Comment by dirk-thomas** [comment]
This is a regression in the latest release. The wrapper folder didn't contain a `__init__.py` file and therefore wasn't installed. I addressed the problem in #348 and will make a new patch release shortly.

@rhaschke I am surprised to hear that. The dependency is correctly declared [here](https://github.com/ros-infrastructure/ros_buildfarm/blob/18909b60ce4e5ed3f6a53671a122ac1ee81f036d/stdeb.cfg#L2-L3) and is also correctly mentioned in the Debian package. I just tried it within a Docker container and empy was pulled in as a dependency. Can you please clarify what exactly you did?

**Comment by dirk-thomas** [comment]
Fix released as version 1.2.1. Debian will be available shortly.

**Comment by 130s** [comment]
I confirmed with `1.2.1-1` the issue is gone. Thank you for the prompt response @dirk-thomas and @rhaschke

**Comment by 130s** [comment]
Didn't know `python-ros-buildfarm` is distributed from http://packages.ros.org (as well as `ros-*` packages). From non-shadow repo I still seem to download 1.2.0. @dirk-thomas Is the newest version going to be available from the official repo at the public sync (if so which one? IJK)? 

Thank you in advance.

**Comment by tfoote** [comment]
@130s it should be in both by now.
