### ISSUE TITLE
beforeFile() missing 1 required positional argument: 'locals'

### ISSUE THREAD

**Issue by lamerman** [ros-infrastructure/ros_buildfarm#389]
I am trying to make a local build to verify that some of my changes work. I follow instructions from here https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/devel_jobs.rst . When I execute the command line from manual:

`generate_devel_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/master/index.yaml indigo default roscpp_core ubuntu trusty amd64 > /tmp/devel_job/devel_job_indigo_roscpp_core.sh`

I see the following error 

```
TypeError processing template 'devel/devel_job.xml.em'
Traceback (most recent call last):
  File "/tmp/deploy_ros_buildfarm/venv/bin/generate_devel_script.py", line 88, in <module>
    sys.exit(main())
  File "/tmp/deploy_ros_buildfarm/venv/bin/generate_devel_script.py", line 69, in main
    jenkins=False, views=False)
  File "/tmp/deploy_ros_buildfarm/ros_buildfarm/ros_buildfarm/devel_job.py", line 307, in configure_devel_job
    is_disabled=is_disabled)
  File "/tmp/deploy_ros_buildfarm/ros_buildfarm/ros_buildfarm/devel_job.py", line 394, in _get_devel_job_config
    job_config = expand_template(template_name, job_data)
  File "/tmp/deploy_ros_buildfarm/ros_buildfarm/ros_buildfarm/templates/__init__.py", line 99, in expand_template
    interpreter.invoke('beforeFile', name=template_name, file=h)
  File "/tmp/deploy_ros_buildfarm/venv/lib/python3.4/site-packages/em.py", line 2640, in invoke
    method(*(), **keywords)
TypeError: beforeFile() missing 1 required positional argument: 'locals'
```

Internally beforeFile is really called without `locals`

```
interpreter.invoke('beforeFile', name=template_name, file=h)
```

While in declaration, the `locals` is present

```
def beforeFile(self, name, file, locals): pass
```

Some information about my system:

```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
```

```
python --version
Python 3.4.4
```

**Comment by dirk-thomas** [comment]
Thank you for reporting the problem. Please see #391 for the proposed fix.
