### ISSUE TITLE
Rescheduling of jobs when executor is out of space fails

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/ros_buildfarm#40]
I believe the rescheduling of jobs when the executor runs out of space is failing in this job:

http://54.183.26.131:8080/job/Jbin_uV32__jsk_roseus__ubuntu_vivid_i386__binary/9/console

I've seen it a couple of times now. Here is the relevant output:

```
# BEGIN SECTION: Check free disk space
10:37:49 Usable disk space = 6558855168 bytes
10:37:49 Free space threshold = 10737418240 bytes
10:37:49 Free disk space is lower than the threshold, aborting this build, disabling the slave, rescheduling the job
10:37:49 # END SECTION
10:37:49 [ssh-agent] Stopped.
10:37:49 FATAL: No signature of method: hudson.model.FreeStyleProject.scheduleBuild() is applicable for argument types: (java.lang.Integer, hudson.model.Cause$UserIdCause, java.util.ArrayList) values: [1, hudson.model.Cause$UserIdCause@92af6756, ...]
10:37:49 Possible solutions: scheduleBuild(), scheduleBuild(int), scheduleBuild(int, hudson.model.Cause), scheduleBuild(int, hudson.model.Cause, [Lhudson.model.Action;), scheduleBuild(hudson.model.Cause), scheduleBuild2(int)
10:37:49 groovy.lang.MissingMethodException: No signature of method: hudson.model.FreeStyleProject.scheduleBuild() is applicable for argument types: (java.lang.Integer, hudson.model.Cause$UserIdCause, java.util.ArrayList) values: [1, hudson.model.Cause$UserIdCause@92af6756, ...]
10:37:49 Possible solutions: scheduleBuild(), scheduleBuild(int), scheduleBuild(int, hudson.model.Cause), scheduleBuild(int, hudson.model.Cause, [Lhudson.model.Action;), scheduleBuild(hudson.model.Cause), scheduleBuild2(int)
10:37:49 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
10:37:49 	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
10:37:49 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
10:37:49 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
10:37:49 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
10:37:49 	at Script1.run(Script1.groovy:42)
10:37:49 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:650)
10:37:49 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:636)
10:37:49 	at hudson.plugins.groovy.SystemGroovy.perform(SystemGroovy.java:93)
10:37:49 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
10:37:49 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
10:37:49 	at hudson.model.Build$BuildExecution.build(Build.java:199)
10:37:49 	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
10:37:49 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
10:37:49 	at hudson.model.Run.execute(Run.java:1759)
10:37:49 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
10:37:49 	at hudson.model.ResourceController.execute(ResourceController.java:89)
10:37:49 	at hudson.model.Executor.run(Executor.java:240)
```

**Comment by wjwwood** [comment]
Here's another example: http://54.183.26.131:8080/job/Jbin_uT32__ecto_image_pipeline__ubuntu_trusty_i386__binary/7/console

**Comment by wjwwood** [comment]
@dirk-thomas thanks for looking into it.
