### ISSUE TITLE
job to generate blocked releases page fails for Lunar

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#406]
This started last night.

http://build.ros.org:8080/job/Lrel_blocked-releases-page/327/console
```
# BEGIN SECTION: Run Dockerfile - blocked_releases page
+ rm -fr /home/jenkins-slave/workspace/Lrel_blocked-releases-page/blocked_releases_page
+ mkdir -p /home/jenkins-slave/workspace/Lrel_blocked-releases-page/blocked_releases_page
+ docker run --rm --cidfile=/home/jenkins-slave/workspace/Lrel_blocked-releases-page/docker_generate_blocked_releases_page/docker.cid --net=host -v /home/jenkins-slave/workspace/Lrel_blocked-releases-page/ros_buildfarm:/tmp/ros_buildfarm:ro -v /home/jenkins-slave/workspace/Lrel_blocked-releases-page/blocked_releases_page:/tmp/blocked_releases_page blocked_releases_page_generation
Checking packages for "lunar" distribution
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/status/build_blocked_releases_page.py", line 44, in <module>
    main()
  File "/tmp/ros_buildfarm/scripts/status/build_blocked_releases_page.py", line 40, in main
    args.output_dir, copy_resources=args.copy_resources)
  File "/tmp/ros_buildfarm/ros_buildfarm/status_page.py", line 558, in build_blocked_releases_page
    repos_data = [_format_repo_table_row(name, data) for name, data in sorted(repos_info.items())]
  File "/tmp/ros_buildfarm/ros_buildfarm/status_page.py", line 558, in <listcomp>
    repos_data = [_format_repo_table_row(name, data) for name, data in sorted(repos_info.items())]
  File "/tmp/ros_buildfarm/ros_buildfarm/status_page.py", line 608, in _format_repo_table_row
    if data['released']:
KeyError: 'released'
Build step 'Execute shell' marked build as failure
SSH: Current build result is [FAILURE], not going to run.
Sending e-mails to: mikael+buildfarm@osrfoundation.org ros-buildfarm-lunar@googlegroups.com
Finished: FAILURE
```

@mikaelarguedas @dhood FYI

**Comment by dhood** [comment]
yep I'm looking into it thanks
