### ISSUE TITLE
doc_independent started failing due to missing pyparsing

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#495]
Failing job: http://build.ros.org/job/doc_independent-packages/

```
+ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.6
making output directory...

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 21, in <module>
    from rosdep2 import __version__  # noqa
  File "../src/rosdep2/__init__.py", line 45, in <module>
    from .lookup import RosdepDefinition, RosdepView, RosdepLookup, \
  File "../src/rosdep2/lookup.py", line 41, in <module>
    from .rospkg_loader import RosPkgLoader
  File "../src/rosdep2/rospkg_loader.py", line 37, in <module>
    import catkin_pkg.package
  File "/tmp/repositories/catkin_pkg/src/catkin_pkg/package.py", line 46, in <module>
    from catkin_pkg.condition import evaluate_condition
  File "/tmp/repositories/catkin_pkg/src/catkin_pkg/condition.py", line 17, in <module>
    import pyparsing
ImportError: No module named pyparsing
```

I believe that it's due to adding pyparsing as a dependency to catkin_pkg
https://github.com/ros-infrastructure/catkin_pkg/pull/197

**Comment by nuclearsandwich** [comment]
This was presumably resolved by the 0.4.0 release of catkin_pkg https://pypi.org/project/catkin_pkg/0.4.0/ as mentioned in #496
