### ISSUE TITLE
generate_all_jobs: failure creating 'Queue' view

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/ros_buildfarm#514]
Has only happened once so far, but thought it would be worth it to track it here: creation of the *Queue* view by the `generate_all_jobs.py` script failed (after a successful `puppet` run) with the following error:

```python-traceback
Connected to Jenkins version '2.89.3'
Creating view 'Queue' of type 'hudson.model.ListView'
Traceback (most recent call last):
  File "/home/user/deploy/venv/bin/generate_all_jobs.py", line 319, in <module>
    main()
  File "/home/user/deploy/venv/bin/generate_all_jobs.py", line 73, in main
    jenkins, 'Queue', filter_queue=False, dry_run=not args.commit)
  File "/home/user/deploy/venv/lib/python3.5/site-packages/ros_buildfarm/jenkins.py", line 101, in configure_view
    if not dry_run else None
  File "/home/user/deploy/venv/lib/python3.5/site-packages/jenkinsapi/views.py", line 132, in create
    headers=headers)
  File "/home/user/deploy/venv/lib/python3.5/site-packages/jenkinsapi/utils/requester.py", line 151, in post_and_confirm_status
    response.text.encode('UTF-8')
jenkinsapi.custom_exceptions.JenkinsAPIException: Operation failed. url=http://master/view/Queue/configure, data={'mode': 'hudson.model.ListView', 'json': '{"mode": "hudson.model.ListView", "name": "Queue"}', 'Submit': 'OK', 'name': 'Queue'}, headers={'Jenkins-Crumb': 'a55d64c42b522d1345ab87b173d4dba6', 'Content-Type': 'application/x-www-form-urlencoded'}, status=404, text=b'<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>\n<title>Error 404 Not Found</title>\n</head>\n<body><h2>HTTP ERROR 404</h2>\n<p>Problem accessing /view/Queue/configure. Reason:\n<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>\n\n</body>\n</html>\n'
```

This was a deployment on Ubuntu Xenial, `amd64`, with `ros_buildfarm` @ 2c8b0bdb0c30d4294d91b3befd98af905298471e.

Jenkins: `2.89.3`.

**Comment by dirk-thomas** [comment]
I just tried to reproduce this and it worked fine for me using `master` against `build.ros2.org` which uses the  same Jenkins version:

```
from ros_buildfarm.jenkins import connect
j = .connect('<url of jenkins>')
from ros_buildfarm.jenkins import configure_view
configure_view(j, 'Queue2', filter_queue=False, dry_run=False)
```

Can you reproduce the problem on your end and provide more information? Thanks.

**Comment by gavanderhoorn** [comment]
Just to clarify: this was on a 'pristine' master (so just after deployment). The only view that existed was `All` (I believe).

On the first run of `generate_all_jobs.py` it failed. After that I ran it a second time and it succeeded.

I'll have to redeploy to reproduce.

**Comment by dirk-thomas** [comment]
I will go ahead and close this for now. If we can ever reproduce the problem this can be reopened.
