### ISSUE TITLE
"NoSuchFileException: collated_test_stats/results.yaml" in recent builds

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/ros_buildfarm#550]
Opening this here to track it: recent builds (such as [this one](http://build.ros.org//job/Mdev__ros_comm__ubuntu_bionic_amd64/41) of `roscpp`) have started running into errors:

```groovy
java.nio.file.NoSuchFileException: collated_test_stats/results.yaml
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at hudson.FilePath$37.invoke(FilePath.java:1922)
	at hudson.FilePath$37.invoke(FilePath.java:1918)
	at hudson.FilePath.act(FilePath.java:998)
	at hudson.FilePath.act(FilePath.java:976)
	at hudson.FilePath.write(FilePath.java:1918)
	at hudson.FilePath$write$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at Script1.run(Script1.groovy:74)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:170)
	at org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder.perform(GroovyPostbuildRecorder.java:362)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
```

Not sure what is going on yet.

Line 74 is ([here](https://github.com/ros-infrastructure/ros_buildfarm/blob/b035d4f5529ebef50387abc5c9e5b39bb2274c79/ros_buildfarm/templates/devel/devel_job.xml.em#L336)):

```
    fp.write(yaml_output, null)
```

`fp != null`, so `def fp = new FilePath(manager.build.workspace, "collated_test_stats/results.yaml")` seems to succeed, but then later when `fp` is used it fails.

**Comment by gavanderhoorn** [comment]
`roscpp` build history ([here](http://build.ros.org/job/Mdev__ros_comm__ubuntu_bionic_amd64)), shows that this started with [build 38](http://build.ros.org/job/Mdev__ros_comm__ubuntu_bionic_amd64/38) (`06-Jun-2018 11:05`).

@nuclearsandwich: any upgrades/updates to the buildfarm around that time that could influence this?

**Comment by gavanderhoorn** [comment]
Just saw this in build `38`:

```
11:15:59 ERROR: Step ‘Scan for compiler warnings’ failed: no workspace for Mdev__ros_comm__ubuntu_bionic_amd64 #38
```

This seems to make more things fail:

```
Build step 'Publish xUnit test result report' marked build as failure
```

and finally results in the tests collation fail, as the `$WORKSPACE/collated_test_stats` is not created.

Creation of that directory is done in [this snippet](https://github.com/ros-infrastructure/ros_buildfarm/blob/b035d4f5529ebef50387abc5c9e5b39bb2274c79/ros_buildfarm/templates/devel/devel_job.xml.em#L239-L247), but that is skipped I believe, as I cannot find the output (`Create collated test stats dir`) in the `roscpp` logs.

---

As this point I'm not sure whether this is something I can fix.

**Comment by gavanderhoorn** [comment]
Spot checking some other builds it seems there are a few other jobs that run into this.

`moveit` is one: [build history](http://build.ros.org/view/Mdev/job/Mdev__moveit__ubuntu_bionic_amd64), [failing build](http://build.ros.org/view/Mdev/job/Mdev__moveit__ubuntu_bionic_amd64/17).

Identical error.

Perhaps I can look into making the collation script more robust against this sort of failures.

**Comment by gavanderhoorn** [comment]
Thanks. I wasn't expecting something to have broken anything, just wanted to make sure.

**Comment by gavanderhoorn** [comment]
Any idea why the workspace disappears / doesn't get created @nuclearsandwich?

That seems right now to be the cause.

I'll see if I can make the script a little more robust. I have a few things I'd like to improve any way.

**Comment by nuclearsandwich** [comment]
> Any idea why the workspace disappears / doesn't get created @nuclearsandwich?

Nothing comes immediately to mind. I was not familiar with the FilePath class and interface
and have been reading up on it [here](http://javadoc.jenkins.io/hudson/FilePath.html).
Do you need to pass any options to the filepath before writing to it?

A digression because of the close inspection: Passing a null encoding to the write method leaves a poor taste in my mouth on https://github.com/ros-infrastructure/ros_buildfarm/blob/b035d4f5529ebef50387abc5c9e5b39bb2274c79/ros_buildfarm/templates/devel/devel_job.xml.em#L336 although if null is the right way to get a default encoding we can attribute the taste to API design. But if we intend this to always write UTF-8 I'd like to see the encoding specified.

Because the issue doesn't fail the build it doesn't generate a notification email to the mailing list, which is my primary way of finding recent example failues.

Is there a failed build whose host is still online to inspect the workspace manually? Right now I've fixed four agent nodes on the buildfarm and I'll leave it there over the weekend instead of letting it scale down to one to preserve more workspaces.

**Comment by gavanderhoorn** [comment]
re: encoding: we can definitely add that.

But I don't believe that is the problem here. The workspace folder should be created much earlier, and I have the impression other errors (ie: in earlier build steps) are already failing because of the workspace 'suddenly' not being there (any longer).

**Comment by nuclearsandwich** [comment]
> But I don't believe that is the problem here.

Nor do I, that was just a bit of drive-by while I was looking for other issues. Apologies for the confusion.

**Comment by nuclearsandwich** [comment]
@gavanderhoorn have you seen any occurrences of this lately? I checked the linked build histories but none seem to have recent failures. I ask because I'd like to let the buildfarm scale back down to a solitary worker.

**Comment by gavanderhoorn** [comment]
@nuclearsandwich: no, I haven't, but I also haven't been paying very close attention. I've had to shift focus to something else.

I've put increasing robustness of the script(s) on my todo list, so I will get to it, but in the meantime please go ahead adjusting the buildfarm again.

**Comment by nuclearsandwich** [comment]
Because these failures happen after the job I don't have an easy way to find them in the mailing list logs either. I'll check back on this every few days but if I can't find a new incident we might consider closing the issue as something environmental at the time. Around June 6 especially there were lots of scaling events that tore down instances that were in the middle of running jobs due to the CPU metrics that trigger scaling.

If nothing else closing an issue is a surefire way to cause it to come back :stuck_out_tongue_winking_eye:

**Comment by dirk-thomas** [comment]
I will close this for now until we see the problem again.
