### ISSUE TITLE
running ./prerelease.sh from master yields an error

### ISSUE THREAD

**Issue by rhaschke** [ros-infrastructure/ros_buildfarm#583]
```
Build step 7
# BEGIN SECTION: Generate Dockerfile - devel tasks
usage: run_devel_job.py [-h] --rosdistro-index-url ROSDISTRO_INDEX_URL
                        [--distribution-repository-urls [DISTRIBUTION_REPOSITORY_URLS [DISTRIBUTION_REPOSITORY_URLS ...]]]
                        [--distribution-repository-key-files [DISTRIBUTION_REPOSITORY_KEY_FILES [DISTRIBUTION_REPOSITORY_KEY_FILES ...]]]
                        [--custom-rosdep-urls [CUSTOM_ROSDEP_URLS [CUSTOM_ROSDEP_URLS ...]]]
                        [--prerelease-overlay]
                        [--dockerfile-dir DOCKERFILE_DIR]
                        rosdistro_name source_build_name repository_name
                        os_name os_code_name arch
run_devel_job.py: error: unrecognized arguments: --env-vars

```

**Comment by dirk-thomas** [comment]
Please share the exact command you ran.

**Comment by dirk-thomas** [comment]
I tried to run your command locally but it failed due to an unknown rosdep key - independently of the version of `ros_buildfarm - `2.0.1` as well as `master`:

```
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 238, in resolve_names
    rosdep_key, view, installer, os_name, os_code_name)
  File "/usr/lib/python3/dist-packages/rosdep2/catkin_support.py", line 87, in resolve_for_os
    d = view.lookup(rosdep_key)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 197, in lookup
    return self.rosdep_defs[rosdep_name]
KeyError: 'planning_models'
```

**Comment by rhaschke** [comment]
This wasn't an issue for me. Sorry can't help more on this. Just wanted to inform you that I got the above error. Maybe it's already fixed now on master.

**Comment by dirk-thomas** [comment]
Sorry, without further information I am going to close this. Please feel free to comment with more information if it happens to still be a problem and the ticket can be reopened.

**Comment by rhaschke** [comment]
No problem. Fully understand.
