### ISSUE TITLE
Builds reporting test statistics collation script failing

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/ros_buildfarm#622]
So far I've got a link to [Mdev__ros_comm__ubuntu_bionic_amd64/133](http://build.ros.org//job/Mdev__ros_comm__ubuntu_bionic_amd64/133/), but I suspect more builds may/will show this.

Stacktrace (shortened to where it mentions the test stat collation script):

```groovy
java.nio.file.AccessDeniedException: /collated_test_stats
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at hudson.FilePath.mkdirs(FilePath.java:3273)
	at hudson.FilePath.access$1300(FilePath.java:213)
	at hudson.FilePath$Write.invoke(FilePath.java:2139)
	at hudson.FilePath$Write.invoke(FilePath.java:2129)
	at hudson.FilePath.act(FilePath.java:1078)
	at hudson.FilePath.act(FilePath.java:1061)
	at hudson.FilePath.write(FilePath.java:2127)
	at hudson.FilePath$write$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at Script1.run(Script1.groovy:74)
        [..]
```

Not sure what is going on (yet), but wanted to at least track this here.

**Comment by dirk-thomas** [comment]
> I don't see any "real" error output in the last lines of the job related to the collation script.

The Groovy script is a post-build action. I can't write any messages to the build log.

**Comment by gavanderhoorn** [comment]
Do you mean the post-build action itself cannot add to the build log? That could be true.

The script itself does appear to be able to write to the log through the `manager` instance. This line fi:

```
Collating test statistics for 'Mdev__ros_comm__ubuntu_bionic_amd64'.
```

is printed [here](https://github.com/ros-infrastructure/ros_buildfarm/blob/4fae75ad9a76a6268011cc129408ca93abbc2a99/ros_buildfarm/templates/devel/devel_job.xml.em#L301).

**Comment by gavanderhoorn** [comment]
Line 74 is most likely this line:

https://github.com/ros-infrastructure/ros_buildfarm/blob/4fae75ad9a76a6268011cc129408ca93abbc2a99/ros_buildfarm/templates/devel/devel_job.xml.em#L340

`fp` is created here:
https://github.com/ros-infrastructure/ros_buildfarm/blob/4fae75ad9a76a6268011cc129408ca93abbc2a99/ros_buildfarm/templates/devel/devel_job.xml.em#L338

If `manager.build.workspace` is an empty string, `fp` could point to `/collated_test_stats` which the groovy runner/jenkins slave is not allowed to write to resulting in the exception.

I've not seen any mention of changes to this part of Jenkins, but as the script was tested on Jenkins `2.89.x` and `build.ros.org` currently runs `2.150.1` things could've changed.

**Comment by gavanderhoorn** [comment]
@nuclearsandwich: could this be a change to the security settings of `build.ros.org`?

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich: could this be a change to the security settings of `build.ros.org`?

The first instance of this failure I see is http://build.ros.org/view/Mdev/job/Mdev__ros_comm__ubuntu_bionic_amd64/128/ (looking only at this job so far). No changes to the buildfarm have been made in April so if this failure is related to new updates (which is possible) it's taken until now to show up. The fact that it's a `java.nio.AccessDeniedException` and the inconsistency make me want to look at filesystem state: Was the file or directory missing or root-owned due to some earlier failure?

I haven't looked at the groovy script yet so the above is just a vague notion.

**Comment by gavanderhoorn** [comment]
Latest build of `ros_comm` shows the same `Groovy` label (ie: script has failed).

I cannot reproduce this here on our deployment.
