### ISSUE TITLE
ros_buildfarm not compatible with jenkinsapi 0.2.27

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#65]
the new version causes this traceback: 

```
Traceback (most recent call last):
  File "/tmp/testvenv/venv/bin/misc/generate_dashboard_job.py", line 41, in <module>
    main()
  File "/tmp/testvenv/venv/bin/misc/generate_dashboard_job.py", line 28, in main
    configure_job(jenkins, job_name, job_config)
  File "/tmp/testvenv/venv/lib/python3.4/site-packages/ros_buildfarm/jenkins.py", line 173, in configure_job
    job = jenkins.create_job(job_name, job_config)
  File "/tmp/testvenv/venv/lib/python3.4/site-packages/jenkinsapi/jenkins.py", line 153, in create_job
    return self.jobs.create(jobname, xml)
  File "/tmp/testvenv/venv/lib/python3.4/site-packages/jenkinsapi/jobs.py", line 119, in create
    params=params
  File "/tmp/testvenv/venv/lib/python3.4/site-packages/jenkinsapi/utils/requester.py", line 118, in post_xml_and_confirm_status
    url, params=params, data=data, headers=headers, valid=valid)
  File "/tmp/testvenv/venv/lib/python3.4/site-packages/jenkinsapi/utils/requester.py", line 126, in post_and_confirm_status
    data)
AssertionError: Unexpected type of parameter 'data': <class 'str'>. Expected (str, dict, bytes)
Traceback (most recent call last):
  File "/tmp/testvenv/venv/bin/generate_all_jobs.py", line 195, in <module>
    main()
  File "/tmp/testvenv/venv/bin/generate_all_jobs.py", line 49, in main
    generate_dashboard_job(args.config_url)
  File "/tmp/testvenv/venv/bin/generate_all_jobs.py", line 98, in generate_dashboard_job
    _check_call(cmd)
  File "/tmp/testvenv/venv/bin/generate_all_jobs.py", line 190, in _check_call
    subprocess.check_call(cmd)
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/testvenv/venv/bin/misc/generate_dashboard_job.py', 'http://b3-repo/tmp/index.yaml']' returned non-zero exit status 1

```

Downgrading to 0.2.26 gets past this issue.

**Comment by dirk-thomas** [comment]
Requested feedback from upstream project about the API change: https://github.com/salimfadhley/jenkinsapi/commit/045eb7572a1b3a043644c3829dbbf72bdfda3912#commitcomment-10972996

**Comment by dirk-thomas** [comment]
The release 0.2.28 fixed the regression upstream.
