### ISSUE TITLE
indigo reconfigure is failing

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#89]
http://54.183.26.131:8080/view/Manage/job/Irel_reconfigure-jobs/

It's been for two weeks now. I think it's a problem with an improperly escaped character. Or else it's something like the script is getting too big or otherwise unloadable.

The last successful build was on the 14th: changes around that time https://github.com/ros/rosdistro/commits/master/indigo/distribution.yaml?page=3

Searches suggesting a bad character or content in the generated script
https://stackoverflow.com/questions/14630404/java-lang-classformaterror-invalid-constant-pool-index-63
https://stackoverflow.com/questions/12333849/classformaterror-unknown-constant-tag-in-class-xy

Exception below. 

```
01:55:16.611 Writing groovy script '/tmp/reconfigure_jobs/reconfigure_jobs.groovy' to reconfigure 10914 jobs
01:55:18.821 + echo # END SECTION
01:55:18.821 # END SECTION
01:55:41.514 FATAL: Invalid this class index 41987 in constant pool in class file Script1
01:55:41.514 java.lang.ClassFormatError: Invalid this class index 41987 in constant pool in class file Script1
01:55:41.514 	at java.lang.ClassLoader.defineClass1(Native Method)
01:55:41.514 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
01:55:41.514 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
01:55:41.514 	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:55)
01:55:41.514 	at groovy.lang.GroovyClassLoader$ClassCollector.createClass(GroovyClassLoader.java:515)
01:55:41.514 	at groovy.lang.GroovyClassLoader$ClassCollector.onClassNode(GroovyClassLoader.java:532)
01:55:41.514 	at groovy.lang.GroovyClassLoader$ClassCollector.call(GroovyClassLoader.java:536)
01:55:41.514 	at org.codehaus.groovy.control.CompilationUnit$14.call(CompilationUnit.java:779)
01:55:41.514 	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:970)
01:55:41.514 	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:548)
01:55:41.514 	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:526)
01:55:41.514 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:503)
01:55:41.514 	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:302)
01:55:41.514 	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:281)
01:55:41.514 	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:731)
01:55:41.514 	at groovy.lang.GroovyShell.parse(GroovyShell.java:743)
01:55:41.514 	at groovy.lang.GroovyShell.parse(GroovyShell.java:698)
01:55:41.514 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:648)
01:55:41.514 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:636)
01:55:41.514 	at hudson.plugins.groovy.SystemGroovy.perform(SystemGroovy.java:93)
01:55:41.514 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
01:55:41.514 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:764)
01:55:41.514 	at hudson.model.Build$BuildExecution.build(Build.java:205)
01:55:41.514 	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
01:55:41.514 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
01:55:41.514 	at hudson.model.Run.execute(Run.java:1744)
01:55:41.514 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
01:55:41.514 	at hudson.model.ResourceController.execute(ResourceController.java:98)
01:55:41.514 	at hudson.model.Executor.run(Executor.java:374)
```

**Comment by tfoote** [comment]
It looks like the problem is that we've got a "constant" which is too big. http://www.groovy-lang.org/mailing-lists.html#nabble-td510151 Strings are constants. 

The groovy script is 129 MB large in the latest workspace with 4.6 million lines. 

It does not appear to be a utf8 issue. That would give a different error message: ` Illegal UTF8 string in constant pool in class file` https://stackoverflow.com/questions/9673511/illegal-utf8-string-in-constant-pool-in-class-file

**Comment by tfoote** [comment]
Some testing shows that a jenkins form entry maxes out at 200000 characters:

```
java.lang.IllegalStateException: Form too large 209924>200000
	at org.eclipse.jetty.server.Request.extractParameters(Request.java:352)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:790)
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:184)
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:184)
	at org.kohsuke.stapler.QueryParameter$HandlerImpl.parse(QueryParameter.java:69)
	at org.kohsuke.stapler.QueryParameter$HandlerImpl.parse(QueryParameter.java:62)
	at org.kohsuke.stapler.AnnotationHandler.handle(AnnotationHandler.java:91)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:153)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:123)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:120)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:198)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:176)
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:85)
	at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:99)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:120)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:114)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Though it's not exactly string length. I found that here: 
```
ERROR: Build step failed with exception
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 1: String too long. The given string is 4508180 Unicode code units long, but only a maximum of 65535 is allowed.
 @ line 1, column 7.
   foo = '''<project>
         ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:302)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:997)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:548)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:526)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:503)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:302)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:281)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:731)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:743)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:698)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:648)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:636)
	at hudson.plugins.groovy.SystemGroovy.perform(SystemGroovy.java:93)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:764)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1744)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Build step 'Execute system Groovy script' marked build as failure
Finished: FAILURE
```

After reviewing the jobs a randomly sampled job description is 20490 characters which is well short of the limit.

**Comment by tfoote** [comment]
Using the tr technique from [here](https://stackoverflow.com/questions/11018967/how-can-i-be-sure-of-the-file-encoding) there are no illegal characters
