### ISSUE TITLE
status jobs broken

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#98]
They're using the old global variable, `template_basename` now `template_prefix_path` changed in #96 

http://54.183.26.131:8080/job/Irel_repos-status-page/17771/console

```
16:30:32 + export PYTHONPATH=/home/jenkins-slave/workspace/Irel_repos-status-page/ros_buildfarm:
16:30:32 + python3 -u /home/jenkins-slave/workspace/Irel_repos-status-page/ros_buildfarm/scripts/status/build_repos_status_page.py http://54.183.65.232/ubuntu/building http://54.183.65.232/ubuntu/testing http://54.183.65.232/ubuntu/main --os-code-name-and-arch-tuples saucy:source saucy:amd64 saucy:i386 trusty:source trusty:amd64 trusty:armhf trusty:i386 --cache-dir /home/jenkins-slave/workspace/Irel_repos-status-page/debian_repo_cache --output-name indigo_default --output-dir /home/jenkins-slave/workspace/Irel_repos-status-page/status_page
16:30:33 Traceback (most recent call last):
16:30:33   File "/home/jenkins-slave/workspace/Irel_repos-status-page/ros_buildfarm/scripts/status/build_repos_status_page.py", line 11, in <module>
16:30:33     from ros_buildfarm.status_page import build_debian_repos_status_page
16:30:33   File "/home/jenkins-slave/workspace/Irel_repos-status-page/ros_buildfarm/ros_buildfarm/status_page.py", line 19, in <module>
16:30:33     from .templates import template_basepath
16:30:33 ImportError: cannot import name 'template_basepath'
```

Also the triggering jobs: http://54.183.26.131:8080/job/Irel_arm_trigger-jobs/16761/

**Comment by dirk-thomas** [comment]
Fixed in b54a816717a899af0cdd512851aeb15ce67cd8a4
